# Site settings
title: ΣΥΣΤΗΜΑ Φροντιστηρια
email: info@systimapylaia.gr
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "systima" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Compress layout - Settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: true

collections:
  other:
    output: true
    permalink: /other/:path
  paroxes:
    output: true
    permalink: /paroxes/:path

defaults:
  - scope:
      path: ""
      type: paroxes
    values:
      layout: default
  - scope:
      path: ""
      type: other
    values:
      layout: default
