# Site settings
title: ΣΥΣΤΗΜΑ Φροντιστηρια
email: info@systimapylaia.gr
description: > # this means to ignore newlines until "baseurl:"

version: 3.0.3
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

JEKYLL_ENV: development

# Compress layout - Settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: true

collections:
  other:
    output: true
    permalink: /other/:path
  leitourgia:
    output: true
    permalink: /leitourgia/:path
  frontistiria:
    output: true
    permalink: /frontistiria/:path
  articles:
    output: true
    permalink: /articles/:path
  news:
    output: true
    permalink: /news/:path
  success:
    output: true
    permalink: /success/:path
  sxoleio:
    output: true
    permalink: /sxoleio/:path
  sxoles:
    output: true
    permalink: /success/:path

defaults:
  - scope:
      path: ""
      type: paroxes
    values:
      layout: default
  - scope:
      path: ""
      type: other
    values:
      layout: default
  - scope:
      path: ""
      type: frontistiria
    values:
      layout: layout-frontistiria
  - scope:
      path: ""
      type: leitourgia
    values:
      layout: layout-leitourgia
